export const selectFields = {
  user: {
    minimal: {
      id: true,
      address: true,
      username: true,
      avatarUrl: true,
    },
    public: {
      id: true,
      address: true,
      username: true,
      avatarUrl: true,
      createdAt: true,
    },
  },

  page: {
    minimal: {
      id: true,
      name: true,
      slug: true,
    },
    card: {
      id: true,
      name: true,
      slug: true,
      tagline: true,
      avatarUrl: true,
      category: true,
      viewCount: true,
    },
    public: {
      id: true,
      name: true,
      slug: true,
      tagline: true,
      description: true,
      avatarUrl: true,
      bannerUrl: true,
      status: true,
      category: true,
      tags: true,
      twitterUrl: true,
      instagramUrl: true,
      websiteUrl: true,
      discordUrl: true,
      benefitsText: true,
      createdAt: true,
      viewCount: true,
      salesCount: true,
    },
  },

  nft: {
    minimal: {
      id: true,
      tokenId: true,
      name: true,
      imageUrl: true,
      price: true,
      status: true,
    },
    card: {
      id: true,
      tokenId: true,
      name: true,
      description: true,
      imageUrl: true,
      price: true,
      status: true,
      ownerId: true,
      pageId: true,
      createdAt: true,
    },
    detail: {
      id: true,
      tokenId: true,
      name: true,
      description: true,
      imageUrl: true,
      metadataUrl: true,
      price: true,
      status: true,
      ownerId: true,
      pageId: true,
      collectionId: true,
      mintedAt: true,
      listedAt: true,
      lastSalePrice: true,
      lastSaleAt: true,
      totalSales: true,
      royaltyPercentage: true,
      royaltyReceiver: true,
      createdAt: true,
      updatedAt: true,
    },
  },

  collection: {
    minimal: {
      id: true,
      name: true,
      slug: true,
    },
    card: {
      id: true,
      name: true,
      slug: true,
      description: true,
      bannerUrl: true,
    },
  },

  activity: {
    list: {
      id: true,
      type: true,
      fromAddress: true,
      toAddress: true,
      price: true,
      transactionHash: true,
      timestamp: true,
    },
  },
};
